version: '3'

services:
  mongodb_container:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
